openapi: 3.0.0
info:
 description: This API provides audit info
 version: "1.0.0"
 title: Audit API
 contact:
  email: kevin_dabu@hotmail.com
paths:
 /pickup:
  get:
   summary: gets a pickup order from history
   operationId: app.get_pickup_order
   description: Gets pickup orders from the event store
   parameters:
    - name: index
      in: query
      description: Gets the PO at the index in the event store
      schema:
       type: integer
       example: 100
   responses:
    '200':
     description: Successfully returned a pickup event
     content:
      application/json:
       schema:
        type: object
        items:
         $ref: '#/components/schemas/PickupOrder'
    '400':
     description: Invalid request
     content:
      application/json:
       schema:
        type: object
        properties:
         message:
          type: string
    '404':
     description: Not Found
     content:
      application/json:
       schema:
        type: object
        properties:
         message:
          type: string
 /delivery:
  get:
   summary: gets a delivery order from history
   operationId: app.get_delivery_order
   description: Gets delivery order from the event store
   parameters:
    - name: index
      in: query
      description: Gets the DO at the index in the event store
      schema:
       type: integer
       example: 100
   responses:
    '200':
     description: Successfully returned a delivery event
     content:
      application/json:
       schema:
        type: object
        items:
         $ref: '#/components/schemas/DeliveryOrder'
    '400':
     description: Invalid request
     content:
      application/json:
       schema:
        type: object
        properties:
         message:
          type: string
    '404':
      description: Not Found

components:
  schemas:
    PickupOrder:
      required:
        - customer_id
        - order_id
      properties:
        customer_id:
          type: string
          example: CUSTOMER_00000
        order_id:
          type: string
          example: ORDER_00000
      type: object

    DeliveryOrder:
      required:
        - customer_id
        - order_id
        - driver_id
      properties:
        customer_id:
          type: string
          example: CUS_00000
        driver_id:
          type: string
          example: DRIVER_000
        order_id:
          type: string
          example: ORDER_00000
      type: object